// GENERATED by contracts_codegen.py — do not edit. Run `just contracts-gen`.

export interface Calibration {
  cleared: number;
  hit_stop: number;
  open: number;
}

export interface ApprovalProposal {
  thesis: string;
  notional: number;
  expected_shortfall: number;
  median: number;
  stress: number;
  red_team: string[];
  tenth_man: string;
  runner_ups: string[];
  tripwires: string[];
  calibration: Calibration;
  cooldown_s: number;
}
