// GENERATED by contracts_codegen.py — do not edit. Run `just contracts-gen`.

export interface Cone {
  horizon: string;
  p5: number[];
  p50: number[];
  p95: number[];
  es_p5: number;
  confidence: number;
  stale: boolean;
}
