// GENERATED by contracts_codegen.py — do not edit. Run `just contracts-gen`.

export interface ApprovalProposal {
  thesis: string;
  notional: number;
  expected_shortfall: number;
  median: number;
  stress: number;
  red_team: string[];
  tenth_man: string;
  runner_ups: string[];
  tripwires: string[];
  calibration: Calibration;
  cooldown_s: number;
}

export interface Calibration {
  cleared: number;
  hit_stop: number;
  open: number;
}

export interface DecisionRow {
  date: string;
  proposal: ApprovalProposal;
  downside_shown: number;
  decision: "approved" | "vetoed";
  outcome: "cleared_cone" | "hit_stop" | "open";
  replayable: boolean;
}
