// GENERATED by contracts_codegen.py — do not edit. Run `just contracts-gen`.

export interface CapitalStructure {
  groww: number;
  zerodha: number;
  reserve: number;
}

export interface DrawdownGuard {
  soft: number;
  hard: number;
}

export interface SelfFunding {
  opex_per_month: number;
  reserve: number;
  covered: boolean;
}

export interface Objective {
  aim: string;
  calmar_target: number;
  calmar_floor: number;
  drawdown_guard: DrawdownGuard;
  horizon: "swing" | "long_term";
  risk_tolerance: "conservative" | "moderate" | "aggressive";
  self_funding: SelfFunding;
  capital_structure: CapitalStructure;
}
