// GENERATED by contracts_codegen.py — do not edit. Run `just contracts-gen`.

export interface Walkforward {
  agg_calmar: number;
  pct_windows_positive: number;
}

export interface TestReport {
  edge_id: string;
  gates_passed: number[];
  pbo: number;
  deflated_sharpe: number;
  haircut_t: number;
  walkforward: Walkforward;
  verdict: "pass" | "fail";
  pre_registered_at?: string | null;
}
