"use client";

import { useState } from "react";

/**
 * Suggested next-step prompts after a reply — tap a chip to send it as the next
 * turn (the chat-app affordance, generated by a cheap follow-up completion).
 */
export function FollowupChips({ chips, onPick }: { chips: string[]; onPick: (q: string) => void }) {
  if (!chips.length) return null;
  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: 7, marginTop: 12 }}>
      {chips.map((c) => (
        <Chip key={c} label={c} onClick={() => onPick(c)} />
      ))}
    </div>
  );
}

function Chip({ label, onClick }: { label: string; onClick: () => void }) {
  const [hov, setHov] = useState(false);
  return (
    <button
      type="button"
      onClick={onClick}
      onMouseEnter={() => setHov(true)}
      onMouseLeave={() => setHov(false)}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        padding: "6px 12px",
        borderRadius: 999,
        cursor: "pointer",
        fontFamily: "Space Grotesk, sans-serif",
        fontSize: 12,
        color: hov ? "var(--fg)" : "var(--fg-2)",
        background: hov
          ? "color-mix(in srgb, var(--accent) 12%, var(--surface-lo))"
          : "color-mix(in srgb, var(--surface-lo) 50%, transparent)",
        border: `1px solid ${hov ? "color-mix(in srgb, var(--accent) 45%, var(--line-hi))" : "var(--line)"}`,
        transition: "all .16s",
      }}
    >
      <span style={{ color: "var(--accent)", fontFamily: "Space Mono, monospace", fontSize: 11 }}>
        ↳
      </span>
      {label}
    </button>
  );
}
