"""Deterministic, $0 codegen: Pydantic contract models → frontend TS types.

Emits one self-contained `{domain}.types.ts` per model (nested `$defs` inlined) plus an
`index.ts` barrel that re-exports each *root* type from its canonical file by name — so a
shared nested model (e.g. `ApprovalProposal`, inlined into its own file and
`decision.types.ts`) never collides. `tests/test_contracts_sync.py` asserts the checked-in
`.ts` matches a fresh `emit_ts`, so the two surfaces can never drift. Run: `just contracts-gen`.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel

from app.modules.contracts.approval_contract import ApprovalProposal
from app.modules.contracts.cone_contract import Cone
from app.modules.contracts.decision_contract import DecisionRow
from app.modules.contracts.feedstate_contract import FeedState
from app.modules.contracts.objective_contract import Objective
from app.modules.contracts.testreport_contract import TestReport

_OUT = Path(__file__).resolve().parents[4] / "frontend" / "src" / "modules" / "contracts"
_HEADER = "// GENERATED by contracts_codegen.py — do not edit. Run `just contracts-gen`.\n\n"

# (model, file stem) — the stem names the {stem}.types.ts file and the barrel export.
MODELS: list[tuple[type[BaseModel], str]] = [
    (Objective, "objective"),
    (TestReport, "testreport"),
    (Cone, "cone"),
    (ApprovalProposal, "approval"),
    (DecisionRow, "decision"),
    (FeedState, "feedstate"),
]
_SCALARS = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _is_nullable(node: dict) -> bool:
    return any(m.get("type") == "null" for m in node.get("anyOf", []))


def _ts_type(node: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "allOf" in node and len(node["allOf"]) == 1:
        return _ts_type(node["allOf"][0])
    if "anyOf" in node:
        return " | ".join(_ts_type(m) for m in node["anyOf"])
    if "const" in node:
        return f'"{node["const"]}"'
    if "enum" in node:
        return " | ".join(f'"{v}"' for v in node["enum"])
    t = node.get("type")
    if t == "array":
        return f"{_ts_type(node.get('items', {}))}[]"
    if t == "object":
        ap = node.get("additionalProperties")
        inner = _ts_type(ap) if isinstance(ap, dict) else "unknown"
        return f"Record<string, {inner}>"
    return _SCALARS.get(t, "unknown")


def _interface(name: str, schema: dict) -> str:
    lines = [f"export interface {name} {{"]
    for field, node in schema.get("properties", {}).items():
        opt = "?" if _is_nullable(node) else ""
        lines.append(f"  {field}{opt}: {_ts_type(node)};")
    lines.append("}")
    return "\n".join(lines)


def emit_ts(model: type[BaseModel]) -> str:
    schema = model.model_json_schema()
    blocks = [_interface(name, sub) for name, sub in sorted(schema.get("$defs", {}).items())]
    blocks.append(_interface(schema["title"], schema))
    return _HEADER + "\n\n".join(blocks) + "\n"


def _barrel() -> str:
    # Sorted by module specifier to satisfy Biome's organize-imports.
    lines = sorted(f'export type {{ {m.__name__} }} from "./{stem}.types";' for m, stem in MODELS)
    return _HEADER + "\n".join(lines) + "\n"


def write_all() -> None:
    _OUT.mkdir(parents=True, exist_ok=True)
    for model, stem in MODELS:
        (_OUT / f"{stem}.types.ts").write_text(emit_ts(model), encoding="utf-8")
    (_OUT / "index.ts").write_text(_barrel(), encoding="utf-8")


if __name__ == "__main__":
    write_all()
    print(f"✓ wrote {len(MODELS)} contract type files + index → {_OUT}")
