"""Suggested follow-ups — up to three short next-step chips after each reply.

Best-effort: generated by a cheap FACTOID completion on the free chain; any
failure returns [] and the chat is unaffected. Chips are plain strings the
frontend renders as one-tap prompts."""

from __future__ import annotations

import json
import re

from alphaforge_anton_llm.types import Message, QueryType

_FENCE = re.compile(r"```(?:json)?\s*(.*?)```", re.DOTALL)

_PROMPT = (
    "You suggest follow-up actions inside an Indian-markets portfolio terminal. "
    "Given the user's question and the assistant's reply, return a JSON array of "
    "exactly 3 short follow-up prompts the user is likely to tap next (max 8 words "
    "each, imperative voice, no numbering, no quotes inside). Return ONLY the JSON "
    "array."
)

MAX_CHIP_CHARS = 60


def parse_followups(text: str) -> list[str]:
    """Tolerant parse of the model's array — fenced or bare; [] on any mismatch."""
    m = _FENCE.search(text)
    raw = m.group(1) if m else text
    try:
        arr = json.loads(raw)
    except (ValueError, json.JSONDecodeError):
        return []
    if not isinstance(arr, list):
        return []
    chips = [str(s).strip()[:MAX_CHIP_CHARS] for s in arr if str(s).strip()]
    return chips[:3]


async def suggest_followups(gateway, user_msg: str, reply: str) -> list[str]:
    """Three tap-to-send chips for the turn, or [] when generation fails."""
    if not user_msg or not reply:
        return []
    try:
        r = await gateway.complete(
            [
                Message(role="system", content=_PROMPT),
                Message(role="user", content=f"Question: {user_msg}\n\nReply: {reply[:1500]}"),
            ],
            query_type=QueryType.FACTOID,
        )
        return parse_followups(r.content)
    except Exception:
        return []
